feat : landing페이지 구현
i-trust-you/wikid pull request #17
Opened 2024-06-29 02:52 UTC by User850413

![제목 없음](https://github.com/i-trust-you/wikid/assets/62880788/38ad27ab-2cf7-4374-905b-7cca49e60f1a)

랜딩 페이지 만들었습니다!
여기서 사용되는 이미지들을 새로 가져왔는데, 혹시 문제가 있으면 알려주세요ㅠㅠ
변수명이 엄청 길어져서 코드가 너무 지저분해 보이지 않나 싶네요
더해서, 수정해야 할 사항 말씀주시면 감사하겠습니다.

### 건의사항
- 일단 landing이라고 폴더명을 정하긴 했는데, main으로 바꾸는게 좋을까요?

2024-06-30 07:00 UTC, heony704 reviewed
저희 랜딩페이지는 요구사항에 `/` 경로에 위치하도록 적혀있습니다.
`/landing` 말고 `/`로 바꿔주세요.

tailwindcss에 맞지 않는 사용방식이 많고 디자인도 피그마와 다른 부분이 많네요.
일정이 촉박하고 하나하나 다 수정사항 요청하고 확인하기에는 번거로울 것 같아서 아래 요청사항만이라도 빠르게 반영해주셨으면 좋겠어요.

- 페이지 경로 `/`으로 수정
- font.css 파일 제거하고 폰트는 global.css에 작성하여 가져다 쓰기 (css 말고 tailwindcss에 맞는 사용방법으로 해주세요)
- svg 파일 png 파일로 변경 (1배 말고 2배 혹은 3배 이미지 사용해주세요)
- 버튼에 링크 연결해주세요

이미지도 돌아가게 만들어주시고 수고하셨어요.
그런데 기본적으로 피그마와 요구사항은 읽어보시고 지켜주셨으면 좋겠습니다 .. 🥹

2024-06-30 07:00 UTC, heony704 commented on app/landing/page.tsx
> +import "./font.css";
이렇게 css 따로 사용하지 마세요.
필요하시다면 global.css 를 이용해주세요.
css 파일을 따로 사용하면 tailwindcss를 사용하는 의미가 없습니다.

2024-06-30 07:00 UTC, heony704 commented on app/landing/page.tsx
> +	const container = "tablet:w-[647px] desktop:w-[924px] w-[335px] mx-auto";
변수로 스타일 관리하지 마시고, 바로 className에 작성해주세요.
스타일이 자주 반복된다는 것은, 스타일 뿐만 아니라 코드가 반복되는 것일 수 있습니다.
반복되는 부분은 차라리 컴포넌트로 만들어 재사용하세요.

2024-06-30 07:00 UTC, heony704 commented on public/images/bell.svg
파일들은 svg 파일이 아닌 png 파일로 사용해주세요.
svg는 벡터의 장점도 있고 간단한 모양의 경우 png보다 용량이 더 작을수도 있습니다.
하지만 이렇게 복잡한 모양은 용량 차이가 매우 커져요.
png 2배 혹은 3배 크기의 이미지를 사용하시는 게 더 나을 것 같아요.

2024-06-30 07:00 UTC, heony704 commented on app/landing/font.css
> +}
클래스 사용하지 마세요

2024-06-30 07:00 UTC, heony704 commented on app/landing/page.tsx
> +				</Link>
링크 연결해주세요

2024-06-30 07:00 UTC, heony704 commented on app/landing/page.tsx
> +				</Link>
여기도 연결해주세요

2024-06-30 10:01 UTC, Programmeryeongtaek requested changes

2024-06-30 10:01 UTC, Programmeryeongtaek commented on app/landing/page.tsx
> +import "./font.css";
저도 이 부분에 동일하게 말씀드려요~
파일을 관리하지 않기 위해, tailwind 사용하기로 했으니까요~~ 변경해주세요오

2024-06-30 10:01 UTC, Programmeryeongtaek commented on app/landing/page.tsx
> +	const container = "tablet:w-[647px] desktop:w-[924px] w-[335px] mx-auto";
저도 이런 실수를 했는데, 
생각해보면 tailwind의 장점은 작성된 태그에서 즉각적인 변경을 눈으로 볼 수 있다는 점인데,
변수로 사용하시면 이점을 활용하지 못할 것 같습니다.

2024-06-30 10:01 UTC, Programmeryeongtaek commented on app/landing/font.css
> +}
해당 파일 코드에서 작성해주세요~
font.css 파일에 대한 피드백과 같습니다!

2024-07-04 02:28 UTC, Programmeryeongtaek reviewed
style UI 에 대한 변경이므로 
커밋 컨벤션 feat가 아니라 style로 해주셔야 해요~

![image](https://github.com/i-trust-you/wikid/assets/87858689/0042a25b-687e-4fe3-bd8c-a40a6970a47c)
주석 처리하신 부분은 지워주시거나 살려주시거나 해주세요~

2024-07-05 05:29 UTC, dotw0xff approved these changes
오우.... 고생 많으셨습니다...

2024-07-05 05:29 UTC, Programmeryeongtaek approved these changes

2024-07-05 05:29 UTC, merged